# **Tiền xử lý dữ liệu**
1. Hiển thị toàn bộ dữ liệu
2. Điền các giá trị bị thiếu của dữ liệu theo phương pháp trung bình với các trường có giá trị số và theo phương pháp tần số cao nhất với giá trị rời rạc
3. Chuẩn hóa dữ liệu theo min max
4. Liên tục hóa thuộc tính variety
5. Rời rạc hóa thuộc tính sepal.length



In [3]:
import pandas as pd
import numpy as np

In [1]:
#Hiển thị toàn bộ dữ liệu
data=pd.read_csv('FLOWER.csv')
data.head()

NameError: name 'pd' is not defined

In [7]:
#Điền các giá trị bị thiếu của dữ liệu theo phương pháp trung bình với các trường có giá trị số và theo phương pháp tần số cao nhất với giá trị rời rạc
data.value_counts()
data.isna().sum()


sepal.length    15
sepal.width     15
petal.length    15
petal.width     15
variety         15
dtype: int64

In [8]:
# prompt: #với sepal.length	sepal.width	petal.length	petal.width ta sẽ điền vào mising value giá trị mean
df1=data.copy()
df1['sepal.length'].fillna(round(df1['sepal.length'].mean()), inplace=True)
df1['sepal.width'].fillna(round(df1['sepal.width'].mean()), inplace=True)
df1['petal.length'].fillna(round(df1['petal.length'].mean()), inplace=True)
df1['petal.width'].fillna(round(df1['petal.width'].mean()), inplace=True)


In [9]:
#với variety ta sẽ thay thế các mising value bằng giá trị có tần số cao nhất
df1['variety'].fillna(data['variety'].mode()[0], inplace = True)
df1.isna().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [10]:
#Chuẩn hóa dữ liệu theo min max
df2 = df1.copy()

sepal_length_max = df2['sepal.length'].max()
sepal_length_min = df2['sepal.length'].min()

sepal_width_max = df2['sepal.width'].max()
sepal_width_min = df2['sepal.width'].min()

petal_length_max = df2['petal.length'].max()
petal_length_min = df2['petal.length'].min()

petal_width_max = df2['petal.width'].max()
petal_width_min = df2['petal.width'].min()

# Chuẩn hóa

df2['sepal.length'] = (df2['sepal.length'] - sepal_length_min) / (sepal_length_max - sepal_length_min)
df2['sepal.width'] = (df2['sepal.width'] - sepal_width_min) / (sepal_width_max - sepal_width_min)
df2['petal.length'] = (df2['petal.length'] - petal_length_min) / (petal_length_max - petal_length_min)
df2['petal.width'] = (df2['petal.width'] - petal_width_min) / (petal_width_max - petal_width_min)

df2



sepal.length  sepal.width  petal.length  petal.width    variety
0        0.222222     0.625000      0.067797     0.041667     Setosa
1        0.166667     0.416667      0.508475     0.041667     Setosa
2        0.111111     0.500000      0.050847     0.041667     Setosa
3        0.083333     0.458333      0.084746     0.375000     Setosa
4        0.194444     0.666667      0.067797     0.041667     Setosa
..            ...          ...           ...          ...        ...
145      0.666667     0.416667      0.711864     0.916667  Virginica
146      0.555556     0.416667      0.677966     0.750000  Virginica
147      0.472222     0.416667      0.711864     0.791667  Virginica
148      0.472222     0.583333      0.508475     0.916667  Virginica
149      0.444444     0.416667      0.694915     0.708333  Virginica

[150 rows x 5 columns]

In [11]:
#Liên tục hóa thuộc tính variety
df3=df2.copy()
dummies=pd.get_dummies(df3['variety'])
df3.head()
df3=pd.concat([df3,dummies],axis=1)
df3.drop('variety',axis=1,inplace=True)


In [12]:
#rời rạc hóa thuộc tính sepal.gth
df4 = df3.copy()

df4['sepal.length'] = pd.cut(df4['sepal.length'],
             bins = [-0.1, 0.2, 0.4, 0.6, 0.8, 1],
             labels = ["Very Low", "Low", "Medium", "High", "Very High"])


# **Xây dựng mô hình hồi quy tuyến tính để đoán kết quả của thuộc tính variety dựa trên các thuộc tính khác**

In [19]:

df=df1.copy()

#chia ra thành train với test
Train= df.drop('variety',axis=1)
Test=df1['variety']


#input:90% để train và 10% để test
tp=int(0.9*len(Train))
X_train=Train[:tp]
Y_train=Test[:tp]
X_test=Train[tp:]
Y_test=Test[tp:]
#xây dựng mô hình
from sklearn.linear_model import RidgeClassifier
reg=RidgeClassifier().fit(X_train,Y_train)
pred=reg.predict(X_test)
reg.score(X_test,Y_test)
target_class=pd.DataFrame( {'Test Value':pred , 'True Value' : Y_test} )
target_class


Test Value True Value
135   Virginica  Virginica
136   Virginica  Virginica
137   Virginica  Virginica
138   Virginica  Virginica
139   Virginica  Virginica
140   Virginica  Virginica
141   Virginica  Virginica
142  Versicolor  Virginica
143   Virginica  Virginica
144   Virginica  Virginica
145   Virginica  Virginica
146   Virginica  Virginica
147   Virginica  Virginica
148   Virginica  Virginica
149   Virginica  Virginica

In [21]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_test, pred)
print("Accuracy:", accuracy)



Accuracy: 0.9333333333333333


In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:, :-1], df.iloc[:, -1], test_size=0.1, random_state=42)

In [29]:
X_train.shape

(135, 4)

# **Thử mấy model dùng để classify để xem model nào classify ra accuracy cao nhất**

1.**KNN**

In [31]:
from sklearn import neighbors
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [32]:

clf = neighbors.KNeighborsClassifier(n_neighbors = 10, weights = 'distance', metric='euclidean')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("KNN accuracy: ", accuracy_score(y_test, y_pred))
print("KNN f1 score: ", f1_score(y_test, y_pred, average='weighted'))
print("KNN confusion matrix: ")
print(confusion_matrix(y_test, y_pred))

KNN accuracy:  0.8666666666666667
KNN f1 score:  0.856060606060606
KNN confusion matrix: 
[[5 0 0]
 [0 5 0]
 [1 1 3]]


2.**Logistic regression**

In [34]:
from sklearn.linear_model import LogisticRegression

In [35]:
regressor = LogisticRegression()
regressor.fit(X_train, y_train)

# predict
predictions = regressor.predict(X_test)
# evaluate
print("LR classification accuracy", accuracy_score(y_test, predictions))

# matrix confusion
cm = confusion_matrix(y_test, predictions)
print(cm)

# f1 score
print("LR f1 score", f1_score(y_test, predictions, average="macro"))


LR classification accuracy 0.7333333333333333
[[5 0 0]
 [0 3 2]
 [1 1 3]]
LR f1 score 0.7252525252525253


ValueError: shapes (100,1) and (4,) not aligned: 1 (dim 1) != 4 (dim 0)